config/routes.rb
Rails.application.routes.draw do

  get '/user/:uid/account', to: 'account#show', as: 'account'
  put '/user/:uid/account', to: 'account#update', as: 'account_update'

  get '/request-match-history', to: 'account#request_match_history', as: 'request_match_history'

  root 'home#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  delete '/logout', to: 'sessions#destroy', as: :logout

  get '/user/:uid/dashboard', to: 'dashboard#index', as: 'dashboard'

  scope '/user/:uid' do
    resources :comparisons
  end

  get '/user/:uid/friends', to: 'friends#index', as: 'friends'

  get '/user/:uid/matches', to: 'matches#index', as: 'matches'

  get '/user/:uid/heroes', to: 'heroes#index', as: 'heroes'

  mount Resque::Server.new, :at => "/resque"

end

app/models/comparison.rb
class Comparison
  include NoBrainer::Document
  include NoBrainer::Document::Timestamps

  belongs_to :user

  field :user_uid, type: Integer
  field :title, type: String
  field :players, type: Array
  field :heroes, type: Array, default: []
end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  before_action :set_comparison, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.where(uid: params[:uid]).first
    @comparisons = @user.comparisons
  end

  def show
  end

  def edit
  end

  def update
    if @comparison.update(comparison_hash)
      redirect_to comparison_path(current_user.uid, @comparison), notice: 'Sucessfully updated comparison'
    else
      render 'edit'
    end
  end

  def create
    @comparison = Comparison.new(comparison_hash)
    if @comparison.save!
      redirect_to comparisons_path(current_user.uid), notice: 'Sucessfully created comparison'
    else
      render 'new'
    end
  end

  def destroy
    if @comparison.destroy
      redirect_to comparisons_path, notice: 'Sucesfully deleted comparison'
    end
  end

  private
    def set_comparison
      @comparison = User.where(uid: params[:uid]).first.comparisons.find(params[:id])
    end

    def comparison_params
      params.require(:comparison).permit(:heroes, :players, :title)
    end

    def comparison_hash
      players = comparison_params["players"].split(",").uniq
      heroes = comparison_params["heroes"].split(",").map(&:to_i).uniq
      { title: comparison_params["title"], user_uid: current_user.uid, players: players, heroes: heroes }
    end
end

app/views/comparisons/edit.html.erb
<%= render 'user_header', user: @user %>
<%= render 'user_navigation', user: @user%>

<section class="module-container">
  <h2 class="ui dividing header">
    <div class="content">
      Editing: <%= @comparison.title %>
    </div>
  </h2>

  <%= form_for @comparison, { url: comparison_path(@current_user.uid, @comparison), method: :put, html: { class: 'ui form' }} do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :players %>
      <div class="ui fluid multiple search selection dropdown">
        <%= f.hidden_field :players, value: @comparison.players.join(",") %>
        <i class="dropdown icon"></i>
        <div class="default text">Select players to compare</div>
        <div class="menu">
          <div class="item" data-value="<%= @current_user.uid %>">
            <img class="ui avatar mini" src="<%= @current_user.image %>">
            <%= @current_user.nickname %>
          </div>
          <% @current_user.friends.each do |friend|%>
            <div class="item" data-value="<%= friend.uid %>">
              <img class="ui avatar mini" src="<%= friend.image %>">
              <%= friend.nickname %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label :heroes %>
      <div class="ui fluid multiple search selection dropdown">
        <%= f.hidden_field :heroes, value: @comparison.heroes.join(",") %>
        <i class="dropdown icon"></i>
        <div class="default text">Select heroes to compare</div>
        <div class="menu">
          <% Dota.api.heroes.each do |hero|%>
            <div class="item" data-value="<%= hero.id %>">
              <img class="ui avatar mini" src="<%= hero.image_url %>">
              <%= hero.name %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.submit 'Save', class: 'ui primary button' %>
    </div>
  <% end %>
</section>

app/views/comparisons/index.html.erb
<%= render 'user_header', user: @user %>
<%= render 'user_navigation', user: @user %>

<section class="module-container">
  <h2 class="ui header">
    <div class="content">
      Comparisons
    </div>
    <% if @current_user.uid == params[:uid].to_i %>
      <%= link_to 'Create', new_comparison_path, class: 'ui right floated small primary button' %>
    <% end %>
  </h2>

  <% if @comparisons.count < 1 %>
    <p>No comparisons available</p>
  <% end %>

  <table class="ui basic table">
    <tbody>
      <% @comparisons.each do |comparison| %>
        <tr>
          <td><%= comparison.title %></td>
          <td class="right aligned">
            <%= link_to 'View', comparison_path(@user.uid, comparison), class: 'ui tiny basic black button' %>
            <% if @current_user.uid == params[:uid].to_i %>
              <%= link_to 'Edit', edit_comparison_path(@user.uid, comparison), class: 'ui tiny basic black button' %>
              <%= link_to 'Delete', comparison_path(@user.uid, comparison), data: { confirm: "Are you sure you want to delete #{comparison.title}" }, method: :delete, class: 'ui tiny basic red button' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/comparisons/new.html.erb
<%= render 'user_header', user: @user %>
<%= render 'user_navigation', user: @user %>

<section class="module-container">
  <h2 class="ui dividing header">
    <div class="content">
      New Comparison
    </div>
  </h2>

  <%= form_for :comparison, { url: comparisons_path, html: { class: 'ui form' }} do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :players %>
      <div class="ui fluid multiple search selection dropdown">
        <%= f.hidden_field :players %>
        <i class="dropdown icon"></i>
        <div class="default text">Select players to compare</div>
        <div class="menu">
          <div class="item" data-value="<%= @current_user.uid %>">
            <img class="ui avatar mini" src="<%= @current_user.image %>">
            <%= @current_user.nickname %>
          </div>
          <% @current_user.friends.each do |friend|%>
            <div class="item" data-value="<%= friend.uid %>">
              <img class="ui avatar mini" src="<%= friend.image %>">
              <%= friend.nickname %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label :heroes %>
      <div class="ui fluid multiple search selection dropdown">
        <%= f.hidden_field :heroes %>
        <i class="dropdown icon"></i>
        <div class="default text">Select heroes to compare</div>
        <div class="menu">
          <% Dota.api.heroes.each do |hero|%>
            <div class="item" data-value="<%= hero.id %>">
              <img class="ui avatar mini" src="<%= hero.image_url %>">
              <%= hero.name %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.submit 'Save', class: 'ui button' %>
    </div>
  <% end %>
</section>

app/views/comparisons/show.html.erb
<%= render 'user_header', user: @user%>
<%= render 'user_navigation', user: @user %>

<section class="module-container">
  <h2 class="ui header">
    <div class="content">
      <%= @comparison.title %>
    </div>
  </h2>

  <% if @comparison.heroes.any? %>
    <h3>Hero selection</h3>
    <div class="ui horizontal list">
      <% @comparison.heroes.each do |hero_id| %>
        <% hero = Dota.api.heroes(hero_id) %>
        <div class="item">
          <img class="ui tiny image dota-hero-image" src="<%= hero.image_url %>"
               data-content="<%= hero.name %>"
               data-variation="inverted">
        </div>
      <% end %>
    </div>
  <% end %>

  <table class="ui basic table">
    <thead>
      <th>
        Player
      </th>
      <th class="right aligned">
        Kills
      </th>
      <th class="right aligned">
        Deaths
      </th>
      <th class="right aligned">
        Last Hits
      </th>
      <th class="right aligned">
        Denies
      </th>
      <th class="right aligned">
        XP per min
      </th>
      <th class="right aligned">
        Net Worth
      </th>
    </thead>
    <tbody>
      <% @comparison.players.each do |player_id| %>
        <%
          player = User.where(uid: player_id).first 
          averages = player.averages([:last_hits, :denies, :kills, :deaths, :xp_per_min, :gold_spent])
        %>
        <tr>
          <td>
            <h5 class="ui image header">
              <img src="<%= player.image %>" class="ui mini image">
              <div class="content">
                <%= player.nickname %>
                <div class="sub header">
                  <%= player.match_summaries.count %> games
                </div>
              </div>
            </h5>
          </td>
          <td class="right aligned">
            <%= averages[:kills].round(2) %>
          </td>
          <td class="right aligned">
            <%= averages[:deaths].round(2) %>
          </td>
          <td class="right aligned">
            <%= averages[:last_hits].round(2) %>
          </td>
          <td class="right aligned">
            <%= averages[:denies].round(2) %>
          </td>
          <td class="right aligned">
            <%= averages[:xp_per_min].round %>
          </td>
          <td class="right aligned">
            <%= averages[:gold_spent].round %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>