config/routes.rb
Rails.application.routes.draw do

  get '/user/:uid/account', to: 'account#show', as: 'account'
  put '/user/:uid/account', to: 'account#update', as: 'account_update'

  get '/request-match-history', to: 'account#request_match_history', as: 'request_match_history'

  root 'home#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  delete '/logout', to: 'sessions#destroy', as: :logout

  get '/user/:uid/dashboard', to: 'dashboard#index', as: 'dashboard'

  scope '/user/:uid' do
    resources :comparisons
  end

  get '/user/:uid/friends', to: 'friends#index', as: 'friends'

  get '/user/:uid/matches', to: 'matches#index', as: 'matches'

  get '/user/:uid/heroes', to: 'heroes#index', as: 'heroes'

  mount Resque::Server.new, :at => "/resque"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :current_user, :user

  private

    def authenticate
      redirect_to root_path unless @current_user
    end

    def current_user
      return nil unless session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end

    def validate_user
      if @current_user.uid.to_s != params[:uid]
        redirect_to account_path(@current_user.uid)
      end
    end

    def user
      begin
        @user = User.where(uid: params[:uid]).first
      rescue
        @user = nil
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include DotaUtil
end

app/views/application/_footer.html.erb
<footer class="page-footer">
  <div class="ui grid">
    <div class="sixteen wide column">
      <div class="ui divider">
      </div>

      <div class="float-left">
        Copyright 2015 DotaFiend. Dota 2 is a registered trademark of Valve Corporation.
      </div>

      <div class="ui float-right horizontal bulleted link list">
        <%= active_link_to 'Home', root_path, class: "item" %>
        <%= active_link_to 'About', root_path, class: "item" %>
      </div>
    </div>
  </div>
</footer>

app/views/application/_matches_table.html.erb
<table class="ui table">
  <thead>
    <tr>
      <th>Hero</th>
      <th>Duration</th>
      <th>Items</th>
      <th>KDA</th>
      <th>Status</th>
      <th>Result</th>
    </tr>
  </thead>
  <tbody>
  <% matches.each do |match| %>
    <tr>
      <td>
        <h5 class="ui image header">
          <img src="<%= DotaUtil.hero_image(match.hero_id) %>" class="ui tiny image">
          <div class="content">
            <%= DotaUtil.hero_name(match.hero_id) %>
            <div class="sub header">
              <%= time_ago_in_words(match.start_time) %> ago
            </div>
          </div>
        </h5>
      </td>
      <td><%= "#{match.duration / 60} Minutes" %></td>
      <td>
        <div class="ui middle aligned mini images">
          <% match.items.each do |item_id| %>
            <% if !DotaUtil.item(item_id).nil? %>
            <img 
              class="image dota-item-image" 
              data-content="<%= DotaUtil.item(item_id).name %>" 
              data-variation="inverted" 
              src="<%= DotaUtil.item(item_id).image_url %>">
            <% end %>
          <% end %>
        </div>
      </td>
      <td>
        <%= "#{match.kills} / #{match.deaths} / #{match.assists}" %>
      </td>
      <td>
        <%= DotaUtil.leaver_status(match.leaver_status) %>
      </td>
      <td>
        <% if match.win %>
          <span class="ui green label">Win</span>
        <% else %>
          <span class="ui red label">Loss</span>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/application/_user_header.html.erb
<%= cache ["user_header", "#{user.uid}#{user.match_summaries.count}"] do %>
  <section>
    <h2 class="ui header">
      <img class="ui image" src="<%= user.image %>" >
      <div class="content">
        <%= user.nickname %>
        <div class="sub header">
          <%= "#{user.match_summaries.count} Matches recorded" %><br>
          <span style="color: #21ba45"><%= user.wins %></span> /
          <span style="color: #db2828"><%= user.losses %></span> /
          <span><%= '%.2f' % (user.win_loss_ratio * 100) %>%</span> 
        </div>
      </div>
    </h2>
  </section>
<% end %>

app/views/application/_user_navigation.html.erb
<div class="ui secondary pointing menu">
  <%= active_link_to 'Dashboard', dashboard_path(user.uid), class: 'item' %>
  <%= active_link_to 'Comparisons', comparisons_path(user.uid), class: 'item' %>
  <%= active_link_to 'Matches', matches_path(user.uid), class: 'item' %>
  <%= active_link_to 'Heroes', heroes_path(user.uid), class: 'item' %>
  <%= active_link_to 'Friends', friends_path(user.uid), class: 'item' %>
</div>