config/routes.rb
Rails.application.routes.draw do

  get '/user/:uid/account', to: 'account#show', as: 'account'
  put '/user/:uid/account', to: 'account#update', as: 'account_update'

  get '/request-match-history', to: 'account#request_match_history', as: 'request_match_history'

  root 'home#index'

  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  delete '/logout', to: 'sessions#destroy', as: :logout

  get '/user/:uid/dashboard', to: 'dashboard#index', as: 'dashboard'

  scope '/user/:uid' do
    resources :comparisons
  end

  get '/user/:uid/friends', to: 'friends#index', as: 'friends'

  get '/user/:uid/matches', to: 'matches#index', as: 'matches'

  get '/user/:uid/heroes', to: 'heroes#index', as: 'heroes'

  mount Resque::Server.new, :at => "/resque"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DotaFiend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="ui inverted segment" style="border-radius: 0;">
    <nav class="ui inverted secondary menu">
    <div class="item">
      <h1 alt="DotaFiend Logo" class="brand">
      <%= image_tag("dotafiend_logo.svg") %>
      </h1>
    </div>
    <div class="right menu">
      <% if @current_user %>
      <div class="item">
        <%= link_to dashboard_path(@current_user.uid) do %>
          <img class="ui mini image" src="<%= @current_user.image %>">
        <% end %>
      </div>
      <div class="ui dropdown item">
        <%= @current_user.nickname %> <i class="dropdown icon"></i>
        <div class="menu">
          <%= link_to 'Dashboard', dashboard_path(@current_user.uid), class: 'item' %>
          <%= link_to 'Comparisons', comparisons_path(@current_user.uid), class: 'item' %>
          <%= link_to 'Account Settings', account_path, class: 'item' %>
          <div class="divider"></div>
          <%= link_to 'Logout', logout_path, method: :delete, class: 'item' %>
        </div>
      </div>
      <% else %>
        <div class="item">
          <%= link_to '/auth/steam', class: 'ui green button' do %>
            <i class="steam icon"></i>
            Sign in with Steam
          <% end %>
        </div>
      <% end %>
    </div>
    </nav>
  </header>

  <main class="ui container">
    <%= semantic_flash %>
    <%= yield %>
    <%= render 'footer' %>
  </main>

</body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FrontEnd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="page-body">
  <div class="ui container">
    <nav class="ui secondary menu">
      <div class="item">
        <h1 alt="DotaFiend Logo" class="brand">
        <%= image_tag("dotafiend_logo.svg") %>
      </div>
      <div class="right menu">
        <% if @current_user %>
          <%= link_to @current_user.nickname, dashboard_path(@current_user.uid), class: 'item'  %>
          <%= link_to 'Logout', logout_path, method: :delete, class: 'item' %>
        <% else %>
          <div class="item">
            <%= link_to 'Sign In', '/auth/steam', class: 'ui basic red button' %>
          </div>
        <% end %>
      </div>
    </nav>
  <div>

  <%= yield %>

  <%= render 'footer' %>
</body>
</html>